### ISSUE TITLE
Hard coded name is a problem

### ISSUE THREAD

**Issue by sletort** [enormandeau/mapcomp#1]
I'm writing bioconda file to in the end integrate mapcomp into a Galaxy instance.
For now, as the input and output are hard coded, it is impossible to integrate mapcomp easily.

I'll modify almost all scripts to use more variable.

I'm in a Galaxy hackathon event.
http://cesgo.genouest.org/groups/guggo/wiki/RADseqHackathon
https://github.com/galaxyproject/tools-iuc/issues/422
https://trello.com/b/EfGYBOPX

**Comment by enormandeau** [comment]
Hi sletort. Interesting project. I chose to use hard coded names for the input and output so that a person could run mapcomp in one shot without having to do the different steps by hand, each time specifying input and output file names.

I think the most minimal approach to modify this behaviour would be to only change the name of the input genome and csv file. These are really the only 2 input files for MapComp.

Let me know how your Galaxy experiment works out!
